spring:
  rabbitmq:
    host: localhost #RabbitMQ host ip
    port: 5672 #RabbitMQ port
    username : guest #RabbitMQ 웹 관리 콘솔아이디
    password : guest #RabbitMQ 웹 관리 콘솔 비밀번호

rabbitmq:
  queue:
    name: sampleQueue
  exchange:
    name: sampleExchange
  routing:
    key: key